import type { User, Subject, Question, Flashcard, StudyGoal } from "./types"

export const mockUser: User = {
  id: "1",
  name: "Candidato PMBA",
  email: "candidato@pmba.com",
  avatar: "/abstract-profile.png",
  createdAt: new Date("2024-01-15"),
  studyGoal: 6,
  currentStreak: 12,
  totalStudyHours: 89,
}

export const mockSubjects: Subject[] = [
  { id: "1", name: "Língua Portuguesa", color: "#3B82F6", totalQuestions: 520 },
  { id: "2", name: "Matemática", color: "#EF4444", totalQuestions: 380 },
  { id: "3", name: "Direito Constitucional", color: "#10B981", totalQuestions: 420 },
  { id: "4", name: "Direito Administrativo", color: "#F59E0B", totalQuestions: 350 },
  { id: "5", name: "Direito Penal", color: "#8B5CF6", totalQuestions: 390 },
  { id: "6", name: "Direito Processual Penal", color: "#EC4899", totalQuestions: 280 },
  { id: "7", name: "Legislação Específica PM", color: "#06B6D4", totalQuestions: 240 },
  { id: "8", name: "Conhecimentos Gerais", color: "#84CC16", totalQuestions: 180 },
]

export const mockQuestions: Question[] = [
  {
    id: "1",
    subjectId: "1",
    question: "Assinale a alternativa que apresenta correta concordância verbal:",
    options: [
      "Fazem dois anos que ele se formou.",
      "Faz dois anos que ele se formou.",
      "Fazem dois anos que eles se formaram.",
      "Faz dois anos que eles se formaram.",
    ],
    correctAnswer: 1,
    explanation:
      'O verbo "fazer" no sentido de tempo decorrido é impessoal, permanecendo sempre na 3ª pessoa do singular.',
    difficulty: "medium",
    year: 2023,
    institution: "PMBA",
  },
  {
    id: "2",
    subjectId: "2",
    question:
      "Um policial militar percorre 240 km em 3 horas. Mantendo a mesma velocidade média, quantos quilômetros percorrerá em 5 horas?",
    options: ["360 km", "380 km", "400 km", "420 km"],
    correctAnswer: 2,
    explanation: "Velocidade média = 240/3 = 80 km/h. Em 5 horas: 80 × 5 = 400 km.",
    difficulty: "easy",
    year: 2023,
    institution: "PMBA",
  },
  {
    id: "3",
    subjectId: "3",
    question: "Segundo a Constituição Federal de 1988, a segurança pública é:",
    options: [
      "Dever exclusivo do Estado",
      "Responsabilidade apenas da Polícia Militar",
      "Dever do Estado, direito e responsabilidade de todos",
      "Competência privativa da União",
    ],
    correctAnswer: 2,
    explanation:
      "Art. 144, CF/88: 'A segurança pública, dever do Estado, direito e responsabilidade de todos, é exercida para a preservação da ordem pública e da incolumidade das pessoas e do patrimônio'.",
    difficulty: "medium",
    year: 2022,
    institution: "PMBA",
  },
  {
    id: "4",
    subjectId: "4",
    question: "O ato administrativo que apresenta vício de competência é:",
    options: ["Anulável", "Nulo", "Inexistente", "Válido"],
    correctAnswer: 1,
    explanation:
      "Atos com vício de competência são nulos, pois a competência é elemento vinculado do ato administrativo.",
    difficulty: "hard",
    year: 2023,
    institution: "PMBA",
  },
  {
    id: "5",
    subjectId: "5",
    question: "O crime de lesão corporal está tipificado no artigo:",
    options: [
      "Art. 128 do Código Penal",
      "Art. 129 do Código Penal",
      "Art. 130 do Código Penal",
      "Art. 131 do Código Penal",
    ],
    correctAnswer: 1,
    explanation:
      "O artigo 129 do Código Penal tipifica o crime de lesão corporal: 'Ofender a integridade corporal ou a saúde de outrem'.",
    difficulty: "medium",
    year: 2022,
    institution: "PMBA",
  },
  {
    id: "6",
    subjectId: "6",
    question: "No processo penal, o princípio da presunção de inocência está previsto:",
    options: [
      "No Código de Processo Penal",
      "Na Constituição Federal, art. 5º, LVII",
      "No Código Penal",
      "Na Lei de Execução Penal",
    ],
    correctAnswer: 1,
    explanation:
      "Art. 5º, LVII, CF/88: 'ninguém será considerado culpado até o trânsito em julgado de sentença penal condenatória'.",
    difficulty: "easy",
    year: 2023,
    institution: "PMBA",
  },
  {
    id: "7",
    subjectId: "7",
    question: "Segundo o Estatuto dos Policiais Militares da Bahia, a hierarquia militar se fundamenta:",
    options: [
      "Apenas na graduação",
      "Na graduação e na antiguidade",
      "Na graduação, antiguidade e disciplina",
      "Exclusivamente na disciplina",
    ],
    correctAnswer: 2,
    explanation:
      "A hierarquia militar se fundamenta na graduação, antiguidade e disciplina, sendo elementos essenciais da organização militar.",
    difficulty: "medium",
    year: 2022,
    institution: "PMBA",
  },
  {
    id: "8",
    subjectId: "8",
    question: "A capital da Bahia é:",
    options: ["Feira de Santana", "Salvador", "Vitória da Conquista", "Ilhéus"],
    correctAnswer: 1,
    explanation: "Salvador é a capital do estado da Bahia e uma das principais cidades do Nordeste brasileiro.",
    difficulty: "easy",
    year: 2023,
    institution: "PMBA",
  },
]

export const mockFlashcards: Flashcard[] = [
  {
    id: "1",
    subjectId: "3",
    front: "Quais são os órgãos de segurança pública segundo a CF/88?",
    back: "Polícia Federal, Polícia Rodoviária Federal, Polícia Ferroviária Federal, Polícias Civis, Polícias Militares e Corpos de Bombeiros Militares (Art. 144, CF/88).",
    difficulty: 2,
    nextReview: new Date(Date.now() + 24 * 60 * 60 * 1000),
    reviewCount: 3,
  },
  {
    id: "2",
    subjectId: "1",
    front: "Quando usar 'onde' e 'aonde'?",
    back: "'Onde' indica lugar em que se está (estático). 'Aonde' indica lugar para onde se vai (movimento). Ex: Onde você mora? / Aonde você vai?",
    difficulty: 1,
    nextReview: new Date(Date.now() - 2 * 60 * 60 * 1000),
    reviewCount: 5,
  },
  {
    id: "3",
    subjectId: "2",
    front: "Como calcular porcentagem?",
    back: "Para calcular x% de um valor: (x/100) × valor. Ex: 15% de 200 = (15/100) × 200 = 0,15 × 200 = 30.",
    difficulty: 2,
    nextReview: new Date(Date.now() - 24 * 60 * 60 * 1000),
    reviewCount: 2,
  },
  {
    id: "4",
    subjectId: "4",
    front: "Quais são os princípios da Administração Pública?",
    back: "LIMPE: Legalidade, Impessoalidade, Moralidade, Publicidade e Eficiência (Art. 37, caput, CF/88).",
    difficulty: 2,
    nextReview: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    reviewCount: 4,
  },
  {
    id: "5",
    subjectId: "5",
    front: "O que é legítima defesa?",
    back: "Excludente de ilicitude. Art. 25, CP: 'Entende-se em legítima defesa quem, usando moderadamente dos meios necessários, repele injusta agressão, atual ou iminente, a direito seu ou de outrem'.",
    difficulty: 3,
    nextReview: new Date(Date.now() - 12 * 60 * 60 * 1000),
    reviewCount: 1,
  },
  {
    id: "6",
    subjectId: "6",
    front: "O que é flagrante delito?",
    back: "Situação em que o crime está sendo cometido, acabou de ser cometido, o agente é perseguido logo após ou é encontrado com objetos que façam presumir ser ele o autor (Art. 302, CPP).",
    difficulty: 3,
    nextReview: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    reviewCount: 6,
  },
  {
    id: "7",
    subjectId: "7",
    front: "Qual a missão da Polícia Militar?",
    back: "Polícia ostensiva e preservação da ordem pública, conforme Art. 144, §5º da CF/88. Atua na prevenção criminal através do policiamento ostensivo.",
    difficulty: 2,
    nextReview: new Date(Date.now() - 6 * 60 * 60 * 1000),
    reviewCount: 8,
  },
  {
    id: "8",
    subjectId: "8",
    front: "Quantos municípios tem a Bahia?",
    back: "A Bahia possui 417 municípios, sendo o estado brasileiro com maior número de municípios.",
    difficulty: 1,
    nextReview: new Date(Date.now() + 24 * 60 * 60 * 1000),
    reviewCount: 3,
  },
]

export const mockStudyGoals: StudyGoal[] = [
  {
    id: "1",
    userId: "1",
    type: "daily",
    target: 6,
    current: 3.5,
    description: "Estudar 6 horas por dia",
    deadline: new Date(),
  },
  {
    id: "2",
    userId: "1",
    type: "weekly",
    target: 300,
    current: 187,
    description: "Resolver 300 questões esta semana",
    deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
  },
]
